# Generated by Django 6.1.1 on 2026-10-08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActorCadena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ASOCIACION", "Asociación"),
                            ("COOPERATIVA", "Cooperativa"),
                            ("COMERCIALIZADOR", "Comercializador"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de actor",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=200, verbose_name="Razón social"),
                ),
                (
                    "nit",
                    models.CharField(max_length=30, unique=True, verbose_name="NIT"),
                ),
                (
                    "contacto",
                    models.CharField(
                        max_length=150,
                        verbose_name="Persona de contacto",
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        max_length=254,
                        verbose_name="Correo electrónico",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="Actor activo"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Actor de la cadena",
                "verbose_name_plural": "Actores de la cadena",
                "db_table": "actores_cadena",
                "ordering": ["razon_social"],
            },
        ),
    ]
