# Generated by Django 6.1.1 on 2026-10-01 16:06

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(unique=True)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modulo', models.TextField()),
                ('activo', models.BooleanField(db_default=True)),
                ('creado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(unique=True)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(db_default=True)),
                ('requiere_cuenta', models.BooleanField(db_default=True, help_text='false = rol sin cuenta/registro (p.ej. Consulta pública vía QR); nunca debe asignarse a una fila real de usuarios.')),
                ('creado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('pk', models.CompositePrimaryKey('rol_id', 'permiso_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('otorgado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Permiso de rol',
                'verbose_name_plural': 'Matriz de permisos por rol (RBAC)',
                'db_table': 'rol_permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(unique=True)),
                ('nombre', models.TextField()),
                ('activo', models.BooleanField(db_default=True)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'db_table': 'tipos_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('numero_documento', models.TextField()),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('telefono', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(db_default=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0, help_text='Contador de intentos de autenticación fallidos consecutivos (RN03)')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Marca temporal hasta la cual la cuenta permanece bloqueada (EX-3)', null=True)),
                ('creado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('actualizado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroIntentoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(db_index=True, help_text='Identificador único (correo o username en minúsculas).', max_length=255, unique=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0, help_text='Número consecutivo de intentos fallidos registrados.')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Marca temporal hasta la cual la cuenta permanece bloqueada.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP de origen del último intento.', null=True)),
                ('ultimo_intento', models.DateTimeField(auto_now=True, help_text='Fecha y hora del intento más reciente.')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario de Django asociado si existe en la plataforma.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos_login', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de intento de login',
                'verbose_name_plural': 'Registros de intentos de login',
                'db_table': 'usuarios_registro_intentos',
                'managed': True,
            },
        ),
    ]
