# Generated by Django 6.1.1 on 2026-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BitacoraCambioRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario_id",
                    models.UUIDField(
                        help_text="id (de auth.users / public.usuarios) de la cuenta cuyo rol cambió."
                    ),
                ),
                (
                    "usuario_correo",
                    models.EmailField(
                        help_text="Correo de la cuenta en el momento del cambio.",
                        max_length=254,
                    ),
                ),
                ("rol_anterior", models.CharField(max_length=50)),
                ("rol_nuevo", models.CharField(max_length=50)),
                (
                    "realizado_por_id",
                    models.UUIDField(
                        blank=True,
                        help_text="id del administrador que ejecutó el cambio, si se pudo determinar.",
                        null=True,
                    ),
                ),
                (
                    "realizado_por_correo",
                    models.EmailField(
                        blank=True,
                        help_text="Correo del administrador que ejecutó el cambio.",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Entrada de bitácora de cambio de rol",
                "verbose_name_plural": "Bitácora de cambios de rol",
                "db_table": "usuarios_bitacora_cambio_rol",
                "ordering": ["-creado_en"],
                "managed": True,
            },
        ),
    ]
