# Generated by Django 6.1.1 on 2026-10-08 19:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0002_bitacoracambiorol"),
    ]

    operations = [
        migrations.CreateModel(
            name="Municipio",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código corto o DANE del municipio (p. ej. 'PAMPLONA').",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "departamento",
                    models.CharField(default="Norte de Santander", max_length=100),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Municipio",
                "verbose_name_plural": "Municipios",
                "db_table": "municipios",
                "ordering": ["nombre"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Finca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre distintivo del predio cafetero.",
                        max_length=150,
                        verbose_name="Nombre de la finca",
                    ),
                ),
                (
                    "vereda",
                    models.CharField(
                        blank=True,
                        help_text="Vereda o sector opcional de ubicación predial.",
                        max_length=150,
                        null=True,
                        verbose_name="Vereda / Sector",
                    ),
                ),
                (
                    "latitud",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Coordenada decimal de latitud [-90, 90]. Campo opcional (RF08).",
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("-90.000000")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("90.000000")
                            ),
                        ],
                        verbose_name="Latitud geográfica",
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Coordenada decimal de longitud [-180, 180]. Campo opcional (RF08).",
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("-180.000000")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("180.000000")
                            ),
                        ],
                        verbose_name="Longitud geográfica",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="Finca activa"),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "productor",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="Perfil de negocio (usuarios.Usuario) dueño/responsable de la finca (RF06).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fincas",
                        to="usuarios.usuario",
                        verbose_name="Productor",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        help_text="Municipio del catálogo donde está ubicada la finca (RF07).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fincas",
                        to="fincas.municipio",
                        verbose_name="Municipio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finca",
                "verbose_name_plural": "Fincas",
                "db_table": "fincas",
                "ordering": ["-creado_en"],
                "managed": True,
            },
        ),
    ]
