# Generated by Django 6.1.1 on 2026-10-07 03:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre distintivo del predio cafetero.', max_length=150, verbose_name='Nombre de la finca')),
                ('municipio', models.CharField(help_text='Municipio donde está ubicada la finca (Norte de Santander).', max_length=100, verbose_name='Municipio')),
                ('vereda', models.CharField(blank=True, help_text='Vereda o sector opcional de ubicación predial.', max_length=150, null=True, verbose_name='Vereda / Sector')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada decimal de latitud [-90.000000, 90.000000]. Campo opcional.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.000000')), django.core.validators.MaxValueValidator(Decimal('90.000000'))], verbose_name='Latitud geográfica')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada decimal de longitud [-180.000000, 180.000000]. Campo opcional.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.000000')), django.core.validators.MaxValueValidator(Decimal('180.000000'))], verbose_name='Longitud geográfica')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la finca se encuentra operativa en el sistema.', verbose_name='Finca activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('productor', models.ForeignKey(blank=True, help_text='Usuario propietario o responsable de la finca.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to=settings.AUTH_USER_MODEL, verbose_name='Productor asignado')),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
                'db_table': 'fincas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
